import Head from 'next/head'
import Main from '../Components/Main'
import Navbar from '../Components/Navbar'
import About from '../components/About'
import Skills from '../Components/Skills'
 
export default function Home() {
  return (
    <div >
      <Head>
        <title>Caleb Ng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar />
    <Main />
    <About />
    <Skills />
      
    </div>
  )
}
